// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcIdxz6Hm-pu9ozdwn1htiSJ85fbdN8W4',
    appId: '1:470408898874:web:c166511345d2dd80de8803',
    messagingSenderId: '470408898874',
    projectId: 'doc-doc-125f7',
    authDomain: 'doc-doc-125f7.firebaseapp.com',
    storageBucket: 'doc-doc-125f7.appspot.com',
    measurementId: 'G-HEEB3MGKF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBql4k6_gOTrqIRZb_Eizdn9SQmgipQH6M',
    appId: '1:470408898874:android:0b2d4cb43ebe2c9ade8803',
    messagingSenderId: '470408898874',
    projectId: 'doc-doc-125f7',
    storageBucket: 'doc-doc-125f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLaSB9VmiaC77sXJdctNQy6NnjiPc_J0',
    appId: '1:470408898874:ios:3157f04fc8082167de8803',
    messagingSenderId: '470408898874',
    projectId: 'doc-doc-125f7',
    storageBucket: 'doc-doc-125f7.appspot.com',
    iosClientId: '470408898874-vreksljog0vfr522mjq9ro7fott0tfip.apps.googleusercontent.com',
    iosBundleId: 'com.example.docDocFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuLaSB9VmiaC77sXJdctNQy6NnjiPc_J0',
    appId: '1:470408898874:ios:3157f04fc8082167de8803',
    messagingSenderId: '470408898874',
    projectId: 'doc-doc-125f7',
    storageBucket: 'doc-doc-125f7.appspot.com',
    iosClientId: '470408898874-vreksljog0vfr522mjq9ro7fott0tfip.apps.googleusercontent.com',
    iosBundleId: 'com.example.docDocFront',
  );
}
